homepage/urls.py
from django.urls import path, reverse_lazy

from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from .views import CustomLoginView

app_name = 'homepage'

urlpatterns = [
    # ex: /(because included in hooslist/urls.py) or /homepage
    path('', views.index, name='home'),
    path('department/<str:department>', views.department, name='department'),
    path('search', views.search, name='search'),
    path('searchfriend', views.searchfriend, name='searchfriend'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('password_change', PasswordChangeView.as_view(success_url=reverse_lazy('homepage:password_change_done')),
         name='password_change'),
    # path('password_change', PasswordChangeView.as_view(),
    #      name='password_change'),
    path('password_change/done', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset', PasswordResetView.as_view(success_url=reverse_lazy("homepage:password_reset_done")),
         name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(success_url=
        reverse_lazy("homepage:password_reset_complete")), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('create_account', views.register, name='register'),
    path('edit', views.edit, name='edit'),
    path('addtolist', views.addToList, name='addtolist'),
    path('removefromlist', views.addToList, name='removefromlist'),
    path('friendslist', views.friendslist, name='friendslist'),
    path('schedule_builder/<int:userID>', views.view_schedule, name='schedule_builder'),
    path('send_friend_request/<int:userID>', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:requestID>', views.accept_friend_request, name='accept_friend_request'),
    path('delete_friend/<int:userID>', views.remove_friend, name='delete_friend'),
    path('cancel_friend_request/<int:requestID>', views.cancel_friend_request, name='cancel_friend_request'),
    path('test', views.showSchedule,name='show_schedule'),
    path('schedule_builder/delete_event/<int:eventID>', views.delete_event, name='delete_event'),
]

hooslist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('', include('homepage.urls'), name='root'), #root url
    path('homepage/', include('homepage.urls'), name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('login', include('homepage.urls'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

homepage/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')


class LoginForm(AuthenticationForm):
    username = UsernameField(
        label='Email or Username',
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match")
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        help_texts = {
            'username': '150 characters or fewer. Letters, digits and @/./+/-/_ only.'
        }


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()

homepage/views.py
from allauth.account.forms import UserForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from datetime import datetime, date
from django.utils.safestring import mark_safe
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, CommentForm, ProfileForm
from .models import Profile, FriendRequest, Friend, CourseModel, Event, Comment
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from django.views import generic
import re
from time import strptime
from .utils import WeeklyTimeTable
from django.http import HttpResponseRedirect


class ScheduleView(generic.ListView):  # this class is no longer used
    model = Event
    template_name = 'homepage/schedule_builder.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['calendar'] = mark_safe("test string")
        return context


def view_schedule(request, userID):
    try:
        schedule_owner = Profile.objects.get(user=User.objects.get(id=userID))
        # get comments associated with schedule
    except User.DoesNotExist:
        return HttpResponse("The user has not created a schedule yet.")
    events = Event.objects.filter(owner=schedule_owner)
    is_owner = request.user == User.objects.get(id=userID)
    html_weekly_timetable = WeeklyTimeTable(schedule_owner, is_owner)
    html_weekly_timetable = mark_safe(html_weekly_timetable.output_entire_calendar())
    comments = Comment.objects.filter(user=User.objects.get(id=userID))
    # new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.user = User.objects.get(id=userID)
            # Save the comment to the database
            new_comment.save()
            comment_form = CommentForm()

    else:
        comment_form = CommentForm()
    return render(request, 'homepage/schedule_builder.html',
                  {'calendar': html_weekly_timetable, 'events': events, 'comments': comments,
                   'comment_form': comment_form}  # add comments to render
                  )


@login_required()
def delete_event(request, eventID):
    current_profile = Profile.objects.get(user=request.user)
    event_selected = Event.objects.get(id=eventID)
    five_digit_num = event_selected.unique_num
    events = Event.objects.filter(unique_num=five_digit_num, owner=current_profile)
    events.delete()
    courses = CourseModel.objects.filter(class_num=five_digit_num, owner_profile=current_profile)
    courses.delete()
    return redirect("homepage:schedule_builder", userID=request.user.id)


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def friend_request(request, pk):
    sender = request.user
    recipient = Profile.objects.get(id=pk)
    model = FriendRequest.objects.get_or_create(sender=request.user, receivers=recipient)
    return render(request, 'homepage/friendslist.html')


def userpage(request):
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    return render(request=request, template_name="homepage/edit.html",
                  context={"user": request.user, "user_form": user_form, "profile_form": profile_form})


@login_required()
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Profile updated successfully')
            # current_profile = Profile.objects.get(user=request.user)
            # courselist = CourseModel.objects.filter(profile_id=current_profile.id)
            # if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
            #     courselist = None
            return HttpResponseRedirect('dashboard')
        else:
            messages.error(request, 'Error in updating the profile')
            return render(request, 'homepage/edit.html', {'user_form': user_form})
    # if request.method:
    #     print("help")
    #     current_profile = Profile.objects.get(user=request.user)
    #     courselist = CourseModel.objects.filter(profile_id=current_profile.id)
    #     if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
    #         courselist = None
    #     return render(request, 'homepage/dashboard.html', {'section': 'dashboard', 'courselist': courselist})
    else:
        # user = request.user
        # current_profile = Profile.objects.get(user=user)
        # courselist = CourseModel.objects.filter(profile_id=current_profile.id)
        # if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
        #     courselist = None
        # return render(request, 'homepage/dashboard.html', {'section': 'dashboard', 'courselist': courselist})
        # print("hi")
        user_form = UserEditForm(instance=request.user)
        return render(request, 'homepage/edit.html', {'user_form': user_form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            email = user_form.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                messages.error(request, 'That email is already in use')
            else:
                new_user = user_form.save(commit=False)
                new_user.set_password(user_form.cleaned_data['password'])
                new_user.save()
                return render(request, 'homepage/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'homepage/register.html', {'user_form': user_form})


@login_required
def dashboard(request):
    user = request.user
    current_profile = Profile.objects.get(user=user)
    courselist = CourseModel.objects.filter(owner_profile=current_profile)
    courselist_json = []
    if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
        courselist = None
    else:
        for each in courselist:
            courselist_dict = {"course_title": each.course_title, "course_acronym": each.course_acronym,
                               "class_num": each.class_num, "course_type": each.course_type,
                               "course_instructor": each.course_instructor}
            if each.course_day_and_time:
                courselist_dict["more_than_one_meeting"] = "yes"
                meeting_list = each.course_day_and_time.split(";")
                courselist_dict["meetings"] = meeting_list
                location_list = each.locations.split(";")
                courselist_dict["locations"] = location_list
            else:
                courselist_dict["course_days"] = each.course_days
                courselist_dict["course_time"] = each.course_time
                courselist_dict["location"] = each.location
            courselist_json.append(courselist_dict)
    return render(request, 'homepage/dashboard.html',
                  {'section': 'dashboard', 'courselist': courselist,
                   'courselist_json': courselist_json})  # , 'user':userID, 'actual_user': person})


def searchfriend(request):
    current_profile = Profile.objects.get(user=request.user)
    profiles_searched = []
    if request.method == "GET":
        search_query = request.GET['friendsearch']
        if len(search_query) > 0:
            # query any profile whose email/username/first/last name contains the search
            search_results_user_model = User.objects.filter(email__icontains=search_query) | \
                                        User.objects.filter(username__icontains=search_query) | \
                                        User.objects.filter(first_name__icontains=search_query) | \
                                        User.objects.filter(last_name__icontains=search_query)
            search_results = []
            for user in search_results_user_model:
                search_results.append(Profile.objects.get(user=user))

            friend_model, created = Friend.objects.get_or_create(current_user=current_profile)
            friends = friend_model.users.all()
            for profile in search_results:
                if len(friends) > 0:
                    is_friend = profile in friends
                else:
                    is_friend = False
                profiles_searched.append((profile, is_friend))
    return friendslist(request, profiles_searched)


def index(request):
    response = requests.get("http://luthers-list.herokuapp.com/api/deptlist/").json()
    result = []
    for x in range(0, len(response) - 15, 16):
        dict = {"first": response[x], "second": response[x + 1], "third": response[x + 2],
                "fourth": response[x + 3], "fifth": response[x + 4], "sixth": response[x + 5],
                "seventh": response[x + 6], "eighth": response[x + 7], "ninth": response[x + 8],
                "tenth": response[x + 9], "eleventh": response[x + 10], "twelve": response[x + 11],

homepage/templates/homepage/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock%}
{% block content %}
{% load static %}

<div class="d-flex justify-content-md-center align-items-center">
    <div class="dashboard">
        <div class="profile-pic">
            <img src="{% static 'homepage/catprofile.png' %}" alt="catprofile" border="0" width="175" height="175"/></a>
        </div>
        <div class="profile-info">
            <h2><u><b>Dashboard</b></u></h2>
            <h2><b>Welcome, {{user.first_name}} {{user.last_name}}!</b></h2>
            <a href="{% url 'homepage:edit' %}" class="btn" role="button" style="margin-left:0px">
                    <button class="button">Edit Profile</button></a>
            <a href="{% url 'homepage:friendslist' %}" class="btn" role="button">
                <button class="button">My Friends</button></a>
            <a href="{% url 'homepage:password_change' %}" class="btn" role="button">
                <button class="button">Change Password</button></a>
            <a href="{% url 'homepage:schedule_builder' user.id %}" class="btn" role="button">
                <button class="button">My Class Schedule</button></a>
        </div>
    </div>
</div>


<br><br>

<h5><b><u><div>Course List: </div></u></b></h5>
<!-- link: https://html5-tutorial.net/tables/changing-column-width/ -->
  <table class="table table-bordered table-hover">

<!--  <col style="width:35%">-->
<!--  <col style="width:17%">-->
<!--  <col style="width:5%">-->
<!--  <col style="width:18%">-->
<!--  <col style="width:25%">-->
  <thead>
  <tr>
    <th><u>Class Title</u></th>
    <th><u>Course Number</u></th>
    <th><u>Type</u></th>
    <th><u>Instructor</u></th>
    <th><u>Time</u></th>
      <th><u>Location</u></th>
  </tr>
  </thead>
  <tbody>

{% if courselist != None %}
        {%for i in courselist_json%}
        <tr>
            <th>
                {{i.course_title}}
            </th>
            <td>
                {{i.course_acronym}} ({{i.class_num}})
            </td>
            <td>
                {{i.course_type}}
            </td>
            <td>
                {{i.course_instructor}}
            </td>

            {% if not i.more_than_one_meeting %}
            <td>
                {{i.course_days}} {{i.course_time}}
            </td>
            <td>
                {{i.location}}
            </td>
            {% else %}
            <td>
                {% for meeting in i.meetings %}
                {{meeting}} <br>
                {% endfor %}
            </td>
            <td>
                {% for location in i.locations %}
                {{location}} <br>
                {% endfor %}
            </td>
            {% endif %}
        </tr>
        {%endfor%}
{% endif %}
</tbody>
</table>

<div>
    <a href="{% url 'homepage:schedule_builder' user.id%}" class="btn" role="button"> <button style="background-color: #87CEEB; padding: 10px; font-size: 16px; margin: 4px 2px; border-radius: 10px;">Calendar View of Courses</button></a>
</div>

<div class = "spacefill"></div>

<style>
.dashboard { /*https://www.webucator.com/article/how-to-create-boxes-with-rounded-corners-in-css/*/
  border-radius: 25px;
  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.2);
  display: flex;
  background: #FFB6C1;
  overflow: hidden;
  width: 1100px;
  margin: 20px;
  max-width: 100%;
}

body{
  margin-align:  center;
}

.profile-pic {
	padding: 20px;
}

.profile-info {
	padding: 30px;
	position: relative;
	width: 100%;
}

.button {
    background-color: #87CEEB;
    padding: 7px;
    font-size: 16px;
    border-radius: 10px;
    position: relative;
    left:-13px;
}
</style>

{% endblock %}
<!--/***************************************************************************************
*  REFERENCES
*  Title: Changing Column Width
*  Author: HTML5 Tutorial
*  URL: https://html5-tutorial.net/tables/changing-column-width/
*  NOTES: help formatting table columns
*
***************************************************************************************/-->


<!--<center>-->
<!--<div id="dashboard">-->
<!--  <h2>-->
<!--    <table class="table">-->
<!--      <thead>-->
<!--        <center> &lt;!&ndash; https://kb.iu.edu/d/abai &ndash;&gt; &lt;!&ndash; https://www.tutorialspoint.com/css/css_positioning.htm &ndash;&gt;-->
<!--            <th scope="col"> <img src="{% static 'homepage/catprofile.png' %}" alt="catprofile" border="0" width="175" height="175" style="margin-bottom: 35px"/></a> </th>-->
<!--            <th scope="col"><div style="margin-top: -200px; margin-left: -601px;"> <u>Dashboard</u></div></th>-->
<!--            <th scope="col"><div style="margin-top: -150px; margin-left: -675px; "> Welcome, {{user.first_name}} {{user.last_name}}! </div>-->
<!--            <th scope="col"><div style="margin-top: -100px; margin-left: -760px;">-->
<!--                <a href="{% url 'homepage:edit' %}" class="btn" role="button">-->
<!--                    <button style="background-color: #87CEEB; padding: 7px; font-size: 16px; margin: 4px 2px; border-radius: 10px;">Edit Profile</button></a>-->
<!--                <a href="{% url 'homepage:friendslist' %}" class="btn" role="button">-->
<!--                    <button style="background-color: #87CEEB; padding: 7px; font-size: 16px; margin: 4px 2px; border-radius: 10px;">My Friends</button></a>-->
<!--                <a href="{% url 'homepage:password_change' %}" class="btn" role="button">-->
<!--                    <button style="background-color: #87CEEB; padding: 7px; font-size: 16px; margin: 4px 2px; border-radius: 10px;">Change Password</button></a>-->
<!--                            </div>-->
<!--            </th>-->
<!--        </center>-->
<!--      </thead>-->
<!--    </table>-->
<!--</center>-->
<!--   </h2>-->
<!--</div>-->
<!--</center>-->

homepage/templates/homepage/friendslist.html
{% extends 'base.html' %}
{% load static %}
{% block extraCSS %}
<link rel="stylesheet" href="{% static 'homepage/css/friendslist.css' %}">
{% endblock%}
{% block content %} <!-- https://github.com/revsys/django-friendship -->

<h1 style="font-family: 'Bebas Neue', cursive;"> My Friends </h1>
<table class="table">
    <div class="row">
        <div>
            <form  id="form1" class="form-inline" method=GET action="{% url 'homepage:searchfriend' %}"> <!-- https://stackoverflow.com/questions/5560975/how-do-i-move-this-to-the-right -->
            {% csrf_token %}
                <input style="font-family: 'fire';" class="form-control" type="text" placeholder="Search User" name="friendsearch">
                <div>
                    <button style="font-family: 'fire'" class="btn btn-outline-secondary my-sm-0" type="submit">Search</button>
                </div>
            </form>
        </div>
    </div>
</table>

{% if is_search_input %}
<div class="card" style="width: 30rem;">
    <div class="card-header">
        {% if profiles_searched %}
        <h6>Search Results</h6>
        {% else %}
        <h6>No Search</h6>
        {% endif %}
    </div>
    {% if profiles_searched %}
    <ul class="list-group list-group-flush">
        {% for i in profiles_searched%}
        <li class="list-group-item">
            <span>{{i.0.user.username}}</span>
            <span style="float: right;">
                {% if i.1 %} <!-- if is a friend-->
                <a class="btn btn-primary btn-sm" href="{% url 'homepage:schedule_builder' i.0.user.id %}"
                        role="button">Schedule</a>
                {% elif i.0 == myself%} <!-- if myself-->
                <a class="btn btn-primary btn-sm" href="{% url 'homepage:dashboard' %}"
                        role="button">My Dashboard</a>
                {% else %} <!-- if not a friend-->
                <a class="btn btn-primary btn-sm" href="{% url 'homepage:send_friend_request' i.0.id %}"
                        role="button">Add Friend</a>
                {% endif %}
            </span>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endif %} <!-- only displays the card view when there's search -->

<!-- modified HTML & CSS code based on https://codepen.io/vivek-kumar/pen/naMJBM -->
<!-- 3-Column CONTAINER -->
<div class="pricing-table group">
    <!-- Friends List -->
    <div class="block personal fl">
        <!-- Header -->
        <div class="content">
            <p class="price">
                <h2>Current Friends</h2>
            </p>
            {% if friends != None %}
            <p class="hint">Click on a friend to see their schedule.</p>
            {% else %}
            <p class="hint">You have no friends yet.</p>
            {% endif %}
        </div>
        <!-- /Header -->
        <!-- List of Friends -->
        <ul class="features">
            {% if friends != None %}
            {% for i in friends %}
            <li>
              <span class="fontawesome-star"></span>
              <span><a href="{% url 'homepage:schedule_builder' i.user.id %}" class="btn btn-secondary btn-sm">{{i.user.username}}</a></span>
              <span>
                <a class="btn btn-primary btn-sm" href="{% url 'homepage:delete_friend' i.id %}"
                        role="button">Delete</a>
              </span>
            </li>
            {% endfor %}
            {% else %}
            {% endif %}
        </ul>
        <!-- /List of Friends -->
    </div>
    <!-- /Friends List -->

    <!-- Requests To Current User -->
    <div class="block professional fl">
        <!-- Header -->
        <div class="content">
            <p class="price">
                <h2>Requests To You</h2>
            </p>
            {% if friend_requests_to_me != None %}
            <p class="hint">Accept or delete a friend request.</p>
            {% else %}
            <p class="hint">No friend requests from other users.</p>
            {% endif %}
        </div>
        <!-- /Header -->
        <!-- Requests to add you. -->
        <ul class="features">
            {% if friend_requests_to_me != None %}
            {% for req in friend_requests_to_me %}
            <li>
                <span class=""></span>
                <span>From: {{req.sender.user}}</span>
                <span>
                    <a class="btn btn-success btn-sm" href="{% url 'homepage:accept_friend_request' req.id %}"
                        role="button">Accept</a>
                    <a class="btn btn-primary btn-sm" href="{% url 'homepage:cancel_friend_request' req.id %}"
                    role="button">Delete</a>
                </span>
            </li>
            {% endfor %}
            {% endif %}
        </ul>
        <!-- /Requests to add you. -->
    </div>
    <!-- /Requests To Current User -->

    <!-- Requests From Current User -->
    <div class="block business fl">
        <!-- Header -->
        <div class="content">
            <p class="price">
              <h2>Requests You Sent</h2>
            </p>
            {% if friend_requests_from_me != None%}
            <p class="hint">You can cancel a friend request.</p>
            {% endif %}
        </div>
        <!-- /Header -->
        <!-- List of Requests -->
        <ul class="features">
            {% if friend_requests_from_me != None%}
            {% for req in friend_requests_from_me %}
            <li>
              <span class="fontawesome-star"></span>
              <span>To: {{req.receiver.user}}</span>
                <span>
                    <a class="btn btn-primary btn-sm"
                            href="{% url 'homepage:cancel_friend_request' req.id %}"
                           role="button">Cancel</a>
                </span>
            </li>
            {% endfor %}
            {% endif %}
        </ul>
        <!-- /List of Requests -->
    </div>
    <!-- /Requests From Current User -->
</div>
<!-- /3-Column Container -->
<div class = "spacefill"/>
{% endblock %}

<!--/***************************************************************************************
*  REFERENCES
*  Title: Flat Pricing Table
*  Author: Codepen: Vivek kumar
*  URL: https://codepen.io/vivek-kumar/pen/naMJBM
*  NOTES: modified HTML & CSS code
*
*  Title: Django-Friendship
*  Author: Jeff Triplett
*  URL:  https://github.com/revsys/django-friendship
*  NOTES: help understanding and implementing friends
*
*  Title: How do I move this to the right?
*  Author: StackOverflow Community
*  URL:   https://stackoverflow.com/questions/5560975/how-do-i-move-this-to-the-right
*  NOTES: help fixing styling for friends
*
***************************************************************************************/-->

homepage/templates/homepage/friendslist_v1.html
{% extends 'base.html' %}
{% block content %}  <!-- https://github.com/revsys/django-friendship -->
<!-- <div class="table-responsive"> -->
<h1 style="font-family: 'Bebas Neue', cursive;"> My Friends </h1>

<table class="table">
    <div class="row">
        <div>
            <form  id="form1" class="form-inline" method=POST action="{% url 'homepage:searchfriend' %}"> <!-- https://stackoverflow.com/questions/5560975/how-do-i-move-this-to-the-right -->
            {% csrf_token %}
                <input style="font-family: 'fire';" class="form-control" type="text" placeholder="Search User" name="friendsearch">
                <div>
                    <button style="font-family: 'fire'" class="btn btn-outline-secondary my-sm-0" type="submit">Search</button>
                </div>
            </form>
        </div>
    </div>
</table>


  <table class="table table-bordered table-hover"> <!-- https://getbootstrap.com/docs/5.1/content/tables/ -->
    <thead>
    <tr>
      <th scope="col">Current Friends</th>
      <th scope="col">Active Friend Requests</th>
      <th scope="col">Pending Friend Requests</th>
    </tr>
  </thead>
<!-- </div> -->
<tbody>
    <tr>
        <td>
            {% if friends != None %}
            <ul style="list-style-type: none; padding: 0px">
                {% for i in friends %}
                <li>
                    <a href="{% url 'homepage:schedule_builder' i.user.id %}" class="btn btn-outline-secondary my-2 my-sm">{{i.user.username}}</a>
                    <a class="btn btn-outline-secondary my-2 my-sm" href="{% url 'homepage:delete_friend' i.id %}"
                        role="button" style="margin-left:10px">Delete</a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <h5>You have no friends yet.</h5>
            {% endif %}
        </td>

        <td>
            {% if friend_requests_to_me != None%}
            <ul style="list-style-type: none">
            {% for fq in friend_requests_to_me %}
                <li>
                From: {{fq.sender.user}}
                <a class="btn btn-outline-secondary my-2 my-sm" href="{% url 'homepage:accept_friend_request' fq.id %}"
                   role="button" style="margin-left:10px">Accept</a>
                    <a class="btn btn-outline-secondary my-2 my-sm" href="{% url 'homepage:cancel_friend_request' fq.id %}"
                   role="button" style="margin-left:10px">Delete</a>
                </li>
            {% endfor %}
            </ul>
            {%else %}
            <h5>No friend requests from other users.</h5>
            {% endif %}
        </td>

        {% if friend_requests_from_me != None%}
        <td>
            <ul>
                {% for fq in friend_requests_from_me %}
                    <li>
                        To: {{fq.receiver.user}} <a class="btn btn-outline-secondary my-2 my-sm"
                            href="{% url 'homepage:cancel_friend_request' fq.id %}"
                           role="button" style="margin-left:10px">Cancel</a>
                    </li>
                {% endfor %}
            </ul>
        </td>
        {% else %}
        <th>
            <h5>You don't have any pending requests.</h5>
        </th>
    {% endif %}
    </tr>




</tbody>
</table>


<!--{% for i in all_users %}-->
<!--        <li>-->
<!--            {{i.user}}{% csrf_token %}-->
<!--            <a class="btn btn-outline-secondary my-2 my-sm" href="{% url 'homepage:send_friend_request' i.id %}"-->
<!--               role="button" style="margin-left:10px">Add Friend</a>-->
<!--        </li>-->
<!--        {% endfor %}-->
<div class = 'spacefill'></div><div class = 'spacefill'></div>
{% endblock %}
<!--/***************************************************************************************
*  REFERENCES
*  Title: How do I move this to the right?
*  Author: StackOverflow Community
*  URL:   https://stackoverflow.com/questions/5560975/how-do-i-move-this-to-the-right
*  NOTES: help fixing styling for friends
*
*  Title: Django-Friendship
*  Author: Jeff Triplett
*  URL:  https://github.com/revsys/django-friendship
*  NOTES: help understanding and implementing friends
*
*  Title: Tables
*  Author: getbootstrap.com Team
*  URL: https://getbootstrap.com/docs/5.1/content/tables/
*  NOTES: styling tables
*
***************************************************************************************/-->