homepage/urls.py
from django.urls import path, reverse_lazy

from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from .views import CustomLoginView

app_name = 'homepage'

urlpatterns = [
    # ex: /(because included in hooslist/urls.py) or /homepage
    path('', views.index, name='home'),
    path('department/<str:department>', views.department, name='department'),
    path('search', views.search, name='search'),
    path('searchfriend', views.searchfriend, name='searchfriend'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('password_change', PasswordChangeView.as_view(success_url=reverse_lazy('homepage:password_change_done')),
         name='password_change'),
    # path('password_change', PasswordChangeView.as_view(),
    #      name='password_change'),
    path('password_change/done', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset', PasswordResetView.as_view(success_url=reverse_lazy("homepage:password_reset_done")),
         name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(success_url=
        reverse_lazy("homepage:password_reset_complete")), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('create_account', views.register, name='register'),
    path('edit', views.edit, name='edit'),
    path('addtolist', views.addToList, name='addtolist'),
    path('removefromlist', views.addToList, name='removefromlist'),
    path('friendslist', views.friendslist, name='friendslist'),
    path('schedule_builder/<int:userID>', views.view_schedule, name='schedule_builder'),
    path('send_friend_request/<int:userID>', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:requestID>', views.accept_friend_request, name='accept_friend_request'),
    path('delete_friend/<int:userID>', views.remove_friend, name='delete_friend'),
    path('cancel_friend_request/<int:requestID>', views.cancel_friend_request, name='cancel_friend_request'),
    path('test', views.showSchedule,name='show_schedule'),
    path('schedule_builder/delete_event/<int:eventID>', views.delete_event, name='delete_event'),
]

hooslist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('', include('homepage.urls'), name='root'), #root url
    path('homepage/', include('homepage.urls'), name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('login', include('homepage.urls'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

homepage/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')


class LoginForm(AuthenticationForm):
    username = UsernameField(
        label='Email or Username',
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match")
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        help_texts = {
            'username': '150 characters or fewer. Letters, digits and @/./+/-/_ only.'
        }


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()

homepage/views.py
from allauth.account.forms import UserForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from datetime import datetime, date
from django.utils.safestring import mark_safe
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, CommentForm, ProfileForm
from .models import Profile, FriendRequest, Friend, CourseModel, Event, Comment
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from django.views import generic
import re
from time import strptime
from .utils import WeeklyTimeTable
from django.http import HttpResponseRedirect


class ScheduleView(generic.ListView):  # this class is no longer used
    model = Event
    template_name = 'homepage/schedule_builder.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['calendar'] = mark_safe("test string")
        return context


def view_schedule(request, userID):
    try:
        schedule_owner = Profile.objects.get(user=User.objects.get(id=userID))
        # get comments associated with schedule
    except User.DoesNotExist:
        return HttpResponse("The user has not created a schedule yet.")
    events = Event.objects.filter(owner=schedule_owner)
    is_owner = request.user == User.objects.get(id=userID)
    html_weekly_timetable = WeeklyTimeTable(schedule_owner, is_owner)
    html_weekly_timetable = mark_safe(html_weekly_timetable.output_entire_calendar())
    comments = Comment.objects.filter(user=User.objects.get(id=userID))
    # new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.user = User.objects.get(id=userID)
            # Save the comment to the database
            new_comment.save()
            comment_form = CommentForm()

    else:
        comment_form = CommentForm()
    return render(request, 'homepage/schedule_builder.html',
                  {'calendar': html_weekly_timetable, 'events': events, 'comments': comments,
                   'comment_form': comment_form}  # add comments to render
                  )


@login_required()
def delete_event(request, eventID):
    current_profile = Profile.objects.get(user=request.user)
    event_selected = Event.objects.get(id=eventID)
    five_digit_num = event_selected.unique_num
    events = Event.objects.filter(unique_num=five_digit_num, owner=current_profile)
    events.delete()
    courses = CourseModel.objects.filter(class_num=five_digit_num, owner_profile=current_profile)
    courses.delete()
    return redirect("homepage:schedule_builder", userID=request.user.id)


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def friend_request(request, pk):
    sender = request.user
    recipient = Profile.objects.get(id=pk)
    model = FriendRequest.objects.get_or_create(sender=request.user, receivers=recipient)
    return render(request, 'homepage/friendslist.html')


def userpage(request):
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    return render(request=request, template_name="homepage/edit.html",
                  context={"user": request.user, "user_form": user_form, "profile_form": profile_form})


@login_required()
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Profile updated successfully')
            # current_profile = Profile.objects.get(user=request.user)
            # courselist = CourseModel.objects.filter(profile_id=current_profile.id)
            # if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
            #     courselist = None
            return HttpResponseRedirect('dashboard')
        else:
            messages.error(request, 'Error in updating the profile')
            return render(request, 'homepage/edit.html', {'user_form': user_form})
    # if request.method:
    #     print("help")
    #     current_profile = Profile.objects.get(user=request.user)
    #     courselist = CourseModel.objects.filter(profile_id=current_profile.id)
    #     if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
    #         courselist = None
    #     return render(request, 'homepage/dashboard.html', {'section': 'dashboard', 'courselist': courselist})
    else:
        # user = request.user
        # current_profile = Profile.objects.get(user=user)
        # courselist = CourseModel.objects.filter(profile_id=current_profile.id)
        # if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
        #     courselist = None
        # return render(request, 'homepage/dashboard.html', {'section': 'dashboard', 'courselist': courselist})
        # print("hi")
        user_form = UserEditForm(instance=request.user)
        return render(request, 'homepage/edit.html', {'user_form': user_form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            email = user_form.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                messages.error(request, 'That email is already in use')
            else:
                new_user = user_form.save(commit=False)
                new_user.set_password(user_form.cleaned_data['password'])
                new_user.save()
                return render(request, 'homepage/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'homepage/register.html', {'user_form': user_form})


@login_required
def dashboard(request):
    user = request.user
    current_profile = Profile.objects.get(user=user)
    courselist = CourseModel.objects.filter(owner_profile=current_profile)
    courselist_json = []
    if len(courselist) == 0:  # initialize to NULL for conditional in html file for printing course table
        courselist = None
    else:
        for each in courselist:
            courselist_dict = {"course_title": each.course_title, "course_acronym": each.course_acronym,
                               "class_num": each.class_num, "course_type": each.course_type,
                               "course_instructor": each.course_instructor}
            if each.course_day_and_time:
                courselist_dict["more_than_one_meeting"] = "yes"
                meeting_list = each.course_day_and_time.split(";")
                courselist_dict["meetings"] = meeting_list
                location_list = each.locations.split(";")
                courselist_dict["locations"] = location_list
            else:
                courselist_dict["course_days"] = each.course_days
                courselist_dict["course_time"] = each.course_time
                courselist_dict["location"] = each.location
            courselist_json.append(courselist_dict)
    return render(request, 'homepage/dashboard.html',
                  {'section': 'dashboard', 'courselist': courselist,
                   'courselist_json': courselist_json})  # , 'user':userID, 'actual_user': person})


def searchfriend(request):
    current_profile = Profile.objects.get(user=request.user)
    profiles_searched = []
    if request.method == "GET":
        search_query = request.GET['friendsearch']
        if len(search_query) > 0:
            # query any profile whose email/username/first/last name contains the search
            search_results_user_model = User.objects.filter(email__icontains=search_query) | \
                                        User.objects.filter(username__icontains=search_query) | \
                                        User.objects.filter(first_name__icontains=search_query) | \
                                        User.objects.filter(last_name__icontains=search_query)
            search_results = []
            for user in search_results_user_model:
                search_results.append(Profile.objects.get(user=user))

            friend_model, created = Friend.objects.get_or_create(current_user=current_profile)
            friends = friend_model.users.all()
            for profile in search_results:
                if len(friends) > 0:
                    is_friend = profile in friends
                else:
                    is_friend = False
                profiles_searched.append((profile, is_friend))
    return friendslist(request, profiles_searched)


def index(request):
    response = requests.get("http://luthers-list.herokuapp.com/api/deptlist/").json()
    result = []
    for x in range(0, len(response) - 15, 16):
        dict = {"first": response[x], "second": response[x + 1], "third": response[x + 2],
                "fourth": response[x + 3], "fifth": response[x + 4], "sixth": response[x + 5],
                "seventh": response[x + 6], "eighth": response[x + 7], "ninth": response[x + 8],
                "tenth": response[x + 9], "eleventh": response[x + 10], "twelve": response[x + 11],

homepage/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        Hoos' List
        {% endblock%}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/calstyle.css' %}">
    {% block extraCSS %}{% endblock%}
    <!--
       *Title: How to add icons in project using Bootstrap?
       *Author: attardeurjita77
       *Date: February 14, 2022
       *Code version: Written using Bootstrap in HTML
       *URL: https://www.geeksforgeeks.org/how-to-add-icons-in-project-using-bootstrap/
        *Software License: N/A
    -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"/>
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
</head>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script> <!-- JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script> <!-- Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg py-2 navbar-light bg-transparent border border-dark rounded"
     style="margin-left: 30px; margin-right: 30px; margin-top: 20px">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage:home' %}" style="font-size: 25px">HoosList</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:schedule_builder' user.id%}" style="color:black">
                        <i class="bi-calendar4-week"></i> My Schedule</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:friendslist'%}" style="color:black">
                        <i class="bi-emoji-smile"></i> My Friends</a>
                </li>
                {% block messageBox %}
                {% endblock %}
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <p style="margin-bottom:1px; color:black; padding: 5px">Welcome, {{user.username}}</p>
                <li><a class="btn btn-outline-dark" href="{% url 'homepage:dashboard'%}" role="button"
                       style="margin-left:20px">My Account</a></li>
                <li><a class="btn btn-outline-dark" href="{% url 'homepage:logout' %}" role="button"
                       style="margin-left:20px">Log out</a></li>
                {% else %}
                <li><a class="btn btn-outline-dark" href="{% url 'homepage:login' %}" role="button">Log in</a></li>
                <li><a class="btn btn-outline-dark" href="{% url 'homepage:register' %}" role="button"
                       style="margin-left:20px">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<br>

</div>


<div class="container">
    {% for message in messages %}
    <div class="container-fluid p-0" data-closeable>
        <div class="alert {{ message.tags }} alert-closable fade show" role="alert">
            <a class="btn btn-outline-secondary my-2 my-sm" href="javascript:window.location.href=window.location.href"
               role="button" style="margin-right:10px">x</a>
            <!--
            *Title: Link to reload current page
            *Author: Markus Amalthea Magnuson
            *Date: August 24, 2012
            *Code version: Written in HTML
            *URL: https://stackoverflow.com/questions/8174282/link-to-reload-current-page
            *Software License: N/A
            -->
            {{ message }}
        </div>
    </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    {% block extraJavascript %}{% endblock%}
</div>


</body>
</html>

homepage/templates/calbase.html
{% extends 'base.html' %}
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" href="{% static 'homepage/calstyle.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}
  {% endblock %}
  {% block script %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  {% endblock %}
</body>